name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-fe:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Get hash for fe directory
      id: hash_fe
      run: echo "HASH_FE=$(git rev-parse HEAD:fe)" >> $GITHUB_ENV

    - name: Get previous hash for fe directory
      id: prev_hash_fe
      run: echo "PREV_HASH_FE=$(git rev-parse HEAD~1:fe)" >> $GITHUB_ENV

    - name: Compare hashes for fe
      run: |
        echo "HASH_FE=${{ env.HASH_FE }}"
        echo "PREV_HASH_FE=${{ env.PREV_HASH_FE }}"
        if [ "${{ env.HASH_FE }}" != "${{ env.PREV_HASH_FE }}" ]; then
          echo "Hashes are different for fe"
          echo "BUILD_FE=true" >> $GITHUB_ENV
        else
          echo "BUILD_FE=false" >> $GITHUB_ENV
        fi

    - name: Get short SHA
      id: vars
      run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

    - name: Build and push Docker image for fe
      if: env.BUILD_FE == 'true'
      uses: docker/build-push-action@v5
      with:
        context: ./fe
        file: ./fe/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/s24-inserter-fe:latest
          ${{ secrets.DOCKER_USERNAME }}/s24-inserter-fe:${{ env.SHORT_SHA }}

  build-orchestrator:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Get hash for orchestrator directory
      id: hash_orchestrator
      run: echo "HASH_ORCHESTRATOR=$(git rev-parse HEAD:orchestrator)" >> $GITHUB_ENV

    - name: Get previous hash for orchestrator directory
      id: prev_hash_orchestrator
      run: echo "PREV_HASH_ORCHESTRATOR=$(git rev-parse HEAD~1:orchestrator)" >> $GITHUB_ENV

    - name: Compare hashes for orchestrator
      run: |
        echo "HASH_ORCHESTRATOR=${{ env.HASH_ORCHESTRATOR }}"
        echo "PREV_HASH_ORCHESTRATOR=${{ env.PREV_HASH_ORCHESTRATOR }}"
        if [ "${{ env.HASH_ORCHESTRATOR }}" != "${{ env.PREV_HASH_ORCHESTRATOR }}" ]; then
          echo "Hashes are different for orchestrator"
          echo "BUILD_ORCHESTRATOR=true" >> $GITHUB_ENV
        else
          echo "BUILD_ORCHESTRATOR=false" >> $GITHUB_ENV
        fi

    - name: Get short SHA
      id: vars
      run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

    - name: Build and push Docker image for orchestrator
      if: env.BUILD_ORCHESTRATOR == 'true'
      uses: docker/build-push-action@v5
      with:
        context: ./orchestrator
        file: ./orchestrator/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/s24-inserter-orchestrator:latest
          ${{ secrets.DOCKER_USERNAME }}/s24-inserter-orchestrator:${{ env.SHORT_SHA }}
